# Tên workflow
name: UniFAQ CI Check

# Kích hoạt khi push hoặc pull request
on: [push, pull_request]

jobs:
  # Tên job
  lint_and_test:
    # Chạy trên Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Lấy code về
      - name: Checkout code
        uses: actions/checkout@v4

      # Cài đặt Node.js LTS, cache npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # Cài đặt dependencies từ package-lock.json
      - name: Install dependencies
        run: npm ci

      # Chạy ESLint
      - name: Run Linter (ESLint)
        run: npm run lint

      # Chạy Jest tests và tạo coverage report
      - name: Run Tests with Coverage (Jest)
        run: npm test -- --coverage

      # Upload thư mục 'coverage' làm artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report # Tên artifact
          path: coverage/       # Đường dẫn tới thư mục coverage